language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - git clone https://github.com/DavidGriffith/frotz.git
  - cd frotz
  - sudo make dfrotz
notifications:
  webhooks:
    - https://salt.kajigga.com/api/hook/flask-app-pushed
  on_success: always # default: always
  on_failure: always # default: always
  on_start: always   # default: never
  on_cancel: always # default: always
  on_error: always # default: always
script:
  - pytest 
